---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tf-jbook-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/tf/notebook
    server: 10.20.0.136

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tf-jbook-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
